version: '3'
services:
  db:
    image: mysql:5.7
    platform: linux/amd64
    environment:
      TZ: Asia/Tokyo
      MYSQL_ROOT_PASSWORD: password
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - 3500:3499
  web:
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    tty: true
    stdin_open: true
    volumes:
      - .:/yfinance
      - bundle_data:/usr/local/bundle:cached
      - node_modules:/yfinance/node_modules
    environment:
      - TZ=Asia/Tokyo
      - SELENIUM_DRIVER_URL=http://chrome:4444/wd/hub
      - PATH=$PATH:/usr/local/bin/python3
    ports:
      - "3000:3000"
    depends_on:
      - db
      - chrome
  chrome:
    image: seleniarm/standalone-chromium:latest
    ports:
      - 4500:4500
volumes:
  mysql_data:
  bundle_data:
  node_modules: